import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const html=await readFile(new URL('../public/index.html',import.meta.url),'utf8');
const css=await readFile(new URL('../public/styles.css',import.meta.url),'utf8');
for(const id of ['appShell','commandCenter','evidenceWorkspace','scenarioWorkspace','proofWorkspace','actionWorkspace','auditWorkspace','systemStatusBar']) test('premium workspace includes #'+id,()=>assert.match(html,new RegExp('id=["\\\']'+id+'["\\\']')));
test('scenario workspace includes direct comparison table',()=>assert.match(html,/id=["']strategyComparison["']/));
test('proof workspace exposes a copy receipt control',()=>assert.match(html,/id=["']copyReceiptBtn["']/));
test('human approval boundary is explicit',()=>assert.match(html,/HUMAN APPROVAL REQUIRED/));
test('external dispatch disclaimer is explicit',()=>assert.match(html,/No supplier, ERP, WMS or external purchasing system is contacted/));
test('simulation disclaimer is explicit',()=>assert.match(html,/Controlled simulation\.<\/b> Not observed retailer outcomes\./));
test('operations first command center anchors exist',()=>{ for(const id of ['incidentCommand','decisionStateCard','nextActionCard']) assert.match(html,new RegExp('id=["\\\']'+id+'["\\\']')); });
test('command center exposes KNOW ASK DECIDE PROVE ACT',()=>{ for(const word of ['KNOW','ASK','DECIDE','PROVE','ACT']) assert.match(html,new RegExp('>'+word+'<')); });
test('opening workspace exposes unresolved evidence and decision state',()=>{assert.match(html,/Unresolved evidence/);assert.match(html,/Decision state/);assert.match(html,/Next best action/);});
test('opening workspace is operational rather than marketing-only',()=>assert.doesNotMatch(html,/class="orb"/));
test('responsive and keyboard accessibility contracts exist',()=>{assert.match(css,/@media\(max-width:390px\)/);assert.match(css,/:focus-visible/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);});
test('signal and evidence investigation anchors exist',()=>{for(const id of ['signalPanel','evidenceMatrix','evidenceScout']) assert.match(html,new RegExp('id=["\\\']'+id+'["\\\']'));});
test('evidence states include Confirmed Estimated Unknown and Stale labels',()=>{for(const label of ['Confirmed','Estimated','Unknown','Stale']) assert.match(html,new RegExp(label));});
test('evidence scout explains why the question matters',()=>{assert.match(html,/WHY THIS MATTERS/);assert.match(html,/decision bottleneck/i);});
